services:
  fipe_consumer:
    build: ./fipe-consumer
    restart: always
    container_name: fipe_consumer
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - redis
      - kafka
      - postgreapi2
    networks:
      - spring_network

  fipe_orchestrator:
    build: ./fipe-orchestrator
    restart: always
    container_name: fipe_orchestrator
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - kafka
      - postgreapi1
    networks:
      - spring_network

  postgreapi1:
    container_name: postgreapi1
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api1
    ports:
      - "5432:5432"
    volumes:
      - db_data1:/var/lib/postgresql
    networks:
      - spring_network

  postgreapi2:
    container_name: postgreapi2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api2
    ports:
      - "5433:5432"
    volumes:
      - db_data2:/var/lib/postgresql
    networks:
      - spring_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spring_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ADDRESS: kafka:9092
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/opt/kafka/data
    networks:
      - spring_network

volumes:
  db_data1:
  db_data2:
  kafka_data:

networks:
  spring_network:
    driver: bridge
